[project]
name = "jsa"
version = "0.1.0"
description = "JSA"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.142.2",
    "finance-datareader>=0.9.202",
    "openpyxl>=3.1.5",
    "plotly>=7.1.0",
    "streamlit>=1.64.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.fastapi]
entrypoint = "app.main:app"

[tool.pytest.ini_options]
testpaths = ["tests"]
